/* Hand-checked question bank. No generated live answers. Reviewed 2026-09-14.
 * Each question has one unambiguous correct choice and a direct source.
 * Stable IDs keep earned rewards when question order changes. */
window.BOSS_QUESTIONS = [
 {id:'wombat-cubes',category:'BODILY NONSENSE',question:'Which animal turns dinner into cube-shaped poo?',choices:['Koala','Wombat','Capybara','Tasmanian devil'],answer:1,explanation:'Wombats produce cube-shaped droppings. Researchers found that the cubes form inside the intestine. Nature apparently has a brick department.',source:'Georgia Tech · Studying Wombats’ Cubic Poop',url:'https://qbios.gatech.edu/studying-wombats-cubic-poop'},
 {id:'flamingo-milk',category:'PARENTING IS WEIRD',question:'A flamingo chick is covered in bright red liquid after feeding. What might it actually be?',choices:['Berry juice','Blood from its parent','Crop milk','Red pond water'],answer:2,explanation:'Flamingos feed chicks a nutritious secretion called crop milk. Pigments make it bright red. It comes from the upper digestive tract, not mammary glands.',source:'Smithsonian’s National Zoo · Raising flamingo chicks',url:'https://www.nationalzoo.si.edu/animals/news/practical-tips-anyone-currently-raising-nine-flamingo-chicks-same-time'},
 {id:'venus-spin',category:'SPACE HAS LOST THE PLOT',question:'Which planet takes longer to spin once on its axis than to orbit the Sun once?',choices:['Mars','Jupiter','Mercury','Venus'],answer:3,explanation:'Venus takes about 243 Earth days to complete one rotation, but about 225 to orbit the Sun. This compares a full rotation with a year—not the interval between sunrises.',source:'NASA · Venus Facts',url:'https://science.nasa.gov/venus/venus-facts/'},
 {id:'banana-berry',category:'FRUIT IDENTITY CRISIS',question:'Botanically speaking, which of these is a berry?',choices:['Banana','Raspberry','Strawberry','Blackberry'],answer:0,explanation:'A banana is a botanical berry. Raspberries and blackberries are aggregate fruits; strawberries are accessory fruits. The fruit bowl has been withholding information.',source:'McGill University · Bananas are Berries. Raspberries are Not.',url:'https://www.mcgill.ca/oss/article/did-you-know/bananas-are-berries-raspberries-are-not'},
 {id:'wood-frog',category:'THE BIOLOGICAL REBOOT',question:'What can a wood frog survive during winter?',choices:['Turning completely into a gas','Freezing, with no heartbeat or breathing','Losing every cell in its body','Being boiled in a hot spring'],answer:1,explanation:'Wood frogs can survive a frozen state without heartbeat or breathing. Ice forms outside cells; protective compounds help prevent the cells themselves from freezing. They thaw and become active again.',source:'US National Park Service · Biological Miracle',url:'https://www.nps.gov/gaar/learn/nature/wood-frog-page-2.htm'},
 {id:'eiffel-sun',category:'BUILDINGS BEHAVING BADLY',question:'As sunshine heats one side of the Eiffel Tower, its top can lean slightly… where?',choices:['Towards the Sun','Always north','Away from the Sun','Straight into the ground'],answer:2,explanation:'The sunlit side expands more than the shaded sides, producing a slight lean away from the Sun. The tower’s operator describes this as normal thermal expansion.',source:'Eiffel Tower official site · Why does the Tower change size?',url:'https://www.toureiffel.paris/en/news/history-and-culture/why-does-eiffel-tower-change-size'},
 {id:'oxford-paris',category:'MEDIEVAL ADMIN DRAMA',question:'Oxford grew rapidly after Henry II banned English students from studying where in 1167?',choices:['The University of Paris','A monastery in Rome','The University of Bologna','The king’s kitchen'],answer:0,explanation:'Oxford’s own history records that it developed rapidly after Henry II banned English students from the University of Paris in 1167, following a quarrel with Thomas Becket. An international argument helped boost a university.',source:'University of Oxford · Our history, 1167',url:'https://www.ox.ac.uk/about/the-university/history'},
 {id:'octopus-brain',category:'QUESTIONABLE PLUMBING',question:'An octopus’s central brain is shaped like a doughnut. What passes through the middle?',choices:['Its ink duct','Its food pipe','Its main artery','A water jet'],answer:1,explanation:'The central brain wraps around the oesophagus—the food pipe. An octopus is, anatomically, eating through the hole in its brain.',source:'Natural History Museum · Octopuses keep surprising us',url:'https://www.nhm.ac.uk/discover/octopuses-keep-surprising-us-here-are-eight-examples-how.html'},
 {id:'argonaut-arm',category:'A VERY STRANGE DATE',question:'A male argonaut octopus can leave what behind with the female during mating?',choices:['Its beak','One of its hearts','A specially modified mating arm','Its entire brain'],answer:2,explanation:'The male argonaut’s specialised sperm-transferring arm can detach and remain with the female. That is quite a commitment to leaving something at her place.',source:'Natural History Museum · Octopuses keep surprising us',url:'https://www.nhm.ac.uk/discover/octopuses-keep-surprising-us-here-are-eight-examples-how.html'},
 {id:'octopus-brood',category:'MOTHER OF ALL WAITING',question:'Researchers observed one deep-sea octopus guarding the same clutch of eggs for how long?',choices:['53 hours','53 days','13 months','53 months'],answer:3,explanation:'A female Graneledone boreopacifica was observed brooding eggs for 53 months—nearly four and a half years. This is a documented observation, not a claim that every octopus does it.',source:'Natural History Museum · 53-month brooding observation',url:'https://www.nhm.ac.uk/discover/octopuses-keep-surprising-us-here-are-eight-examples-how.html'}
];

/* One new pair per mastered question; skin and motion can be mixed independently. */
window.BOSS_REWARDS = [
 {id:'sherbet',name:'Sherbet riot',motion:'Float',colors:['#fff0d8','#ff665b','#f6b334','#2b2042'],frames:[{transform:'translateY(0)'},{transform:'translateY(-18px)'},{transform:'translateY(0)'}]},
 {id:'flamingo',name:'Flamingo club',motion:'Pendulum',colors:['#ffe2f0','#e9418b','#8058ef','#352044'],frames:[{transform:'rotate(0)'},{transform:'rotate(9deg)'},{transform:'rotate(-7deg)'},{transform:'rotate(0)'}]},
 {id:'cosmic',name:'Cosmic jelly',motion:'Full orbit',colors:['#19152e','#ad97ff','#ffb651','#f8eeff'],frames:[{transform:'rotate(0)'},{transform:'rotate(360deg)'}]},
 {id:'banana',name:'Banana drama',motion:'Jelly bounce',colors:['#fff5ad','#b16d16','#e95587','#342414'],frames:[{transform:'scale(1)'},{transform:'scale(1.08,.9)'},{transform:'scale(.94,1.07)'},{transform:'scale(1)'}]},
 {id:'frost',name:'Frost goblin',motion:'Thaw & bloom',colors:['#ddf7f4','#298c9a','#835ddb','#173c46'],frames:[{transform:'scale(.82)',filter:'blur(3px)'},{transform:'scale(1.035)',filter:'blur(0px)'},{transform:'scale(1)'}]},
 {id:'solar',name:'Solar punk',motion:'Sun dance',colors:['#fce1bb','#d34b18','#477b4c','#3d2a1b'],frames:[{transform:'translate(0,0)'},{transform:'translate(12px,-10px)'},{transform:'translate(-12px,-10px)'},{transform:'translate(0,0)'}]},
 {id:'royal',name:'Royal trouble',motion:'Curtsey',colors:['#ece0ff','#8142c1','#c18119','#302043'],frames:[{transform:'perspective(800px) rotateX(0)'},{transform:'perspective(800px) rotateX(22deg) translateY(8px)'},{transform:'perspective(800px) rotateX(0)'}]},
 {id:'ink',name:'Ink after dark',motion:'Sideways shuffle',colors:['#162830','#60c9bc','#de8bb2','#edf8f4'],frames:[{transform:'translateX(0)'},{transform:'translateX(14px) rotate(5deg)'},{transform:'translateX(-14px) rotate(-5deg)'},{transform:'translateX(0)'}]},
 {id:'electric',name:'Electric affair',motion:'Double hop',colors:['#eeecff','#6749ef','#dc386f','#2b2045'],frames:[{transform:'translateY(0)'},{transform:'translateY(-20px)',offset:.25},{transform:'translateY(0)',offset:.5},{transform:'translateY(-10px)',offset:.75},{transform:'translateY(0)'}]},
 {id:'boss',name:'BOSS level',motion:'Victory flourish',colors:['#24201e','#ffd568','#ff829f','#fff4d7'],frames:[{transform:'rotate(0) scale(1)'},{transform:'rotate(-10deg) scale(.9)'},{transform:'rotate(370deg) scale(1.05)'},{transform:'rotate(360deg) scale(1)'}]}
];
