(() => {
 'use strict';
 if (!window.JUICE_PLAY.bossEdition) return;
 const questions=window.BOSS_QUESTIONS,rewards=window.BOSS_REWARDS,$=id=>document.getElementById(id);
 const key='juice-play:boss:trivia-v1',valid=new Set(questions.map(q=>q.id));
 let state={solved:[],skin:null,motion:null},persistent=true,current=null,answered=false,activeAnimation;
 try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&Array.isArray(saved.solved)){state.solved=[...new Set(saved.solved.filter(id=>valid.has(id)))];state.skin=saved.skin;state.motion=saved.motion;}}catch{}
 const unlocked=()=>rewards.slice(0,state.solved.length);
 const allowed=id=>unlocked().some(r=>r.id===id);
 if(!allowed(state.skin))state.skin=null;if(!allowed(state.motion))state.motion=null;
 function persist(){try{localStorage.setItem(key,JSON.stringify(state));persistent=true;}catch{persistent=false;}$('boss-save-note').textContent=persistent?'Progress stays on this device.':'Progress lasts for this visit only: browser storage is unavailable.';}
 const shell=document.createElement('section');shell.id='boss-trivia';shell.innerHTML=`
 <div class="boss-launch"><div><span class="boss-kicker">BOSS / THE WTF FILES</span><h2>Reality is taking the piss.</h2><p id="boss-progress"></p></div><button id="boss-open" class="boss-primary">Ask me something weird ↗</button></div>
 <details class="boss-collection"><summary>Your unlocked toys <span id="boss-count"></span></summary><p>Pick a skin. Mix in a move.</p><div id="boss-rewards" class="boss-reward-grid"></div><div class="boss-motion-row"><label for="boss-motion">Clock move<select id="boss-motion"><option value="">Classic bounce</option></select></label><button id="boss-preview" class="boss-secondary">Play move ✳</button></div><p id="boss-save-note" class="boss-note"></p><p id="boss-motion-note" class="boss-note"></p></details>`;
 document.querySelector('.skins').after(shell);
 const badge=document.createElement('button');badge.id='boss-shortcut';badge.className='boss-shortcut';badge.textContent='WTF? Earn a new skin ↓';badge.addEventListener('click',open);document.querySelector('.intro').append(badge);
 const dialog=document.createElement('dialog');dialog.id='boss-quiz';dialog.setAttribute('aria-labelledby','boss-question');dialog.innerHTML=`<form method="dialog"><button class="close" aria-label="Close trivia">×</button></form><div class="boss-kicker" id="boss-category"></div><p class="boss-question-count" id="boss-question-count"></p><h2 id="boss-question" tabindex="-1"></h2><p class="boss-prize" id="boss-prize"></p><div id="boss-choices" class="boss-choices"></div><div id="boss-feedback" role="status" aria-live="polite"></div><div id="boss-reveal" hidden><p id="boss-explanation"></p><a id="boss-source" target="_blank" rel="noopener noreferrer">Check the evidence ↗</a><div class="boss-reveal-actions"><button id="boss-wear" class="boss-secondary">Try my new toys ✳</button><button id="boss-next" class="boss-primary">Next weird fact →</button></div></div>`;
 document.body.append(dialog);
 const tokenNames=['paper','ink','muted','face','edge','rim','hour-top','hour','hour-shadow','minute-top','minute','minute-shadow','bead','accent','knob','shadow'];
 function clearSkin(){tokenNames.forEach(name=>document.body.style.removeProperty('--'+name));}
 function wear(id){const r=unlocked().find(x=>x.id===id);if(!r)return;window.JuiceClock.setSkin('citrus');const [paper,a,b,ink]=r.colors;
 const mix=(c,withColor,pct)=>`color-mix(in srgb, ${c} ${pct}%, ${withColor})`;
 const tokens={paper,ink,muted:mix(ink,paper,72),face:mix(paper,ink,94),edge:mix(paper,'white',75),rim:mix(paper,ink,82),'hour-top':mix(a,'white',65),hour:a,'hour-shadow':mix(a,'black',60),'minute-top':mix(b,'white',65),minute:b,'minute-shadow':mix(b,'black',60),bead:b,accent:a,knob:mix(a,paper,50),shadow:'rgba(0,0,0,.22)'};
 for(const [name,value]of Object.entries(tokens))document.body.style.setProperty('--'+name,value);
 document.querySelector('meta[name=theme-color]').content=paper;document.querySelectorAll('[name=skin]').forEach(el=>el.checked=false);state.skin=id;persist();updateCollectionSelection();}
 document.addEventListener('juice:skin',()=>{clearSkin();state.skin=null;persist();updateCollectionSelection();});
 function play(){$('boss-motion-note').textContent='';const r=unlocked().find(x=>x.id===state.motion);if(!r){window.JuiceClock.bounce();return;}activeAnimation?.cancel();if(matchMedia('(prefers-reduced-motion: reduce)').matches){$('boss-motion-note').textContent=r.motion+' is unlocked. Motion is paused by your device’s Reduce Motion setting.';return;}const target=document.querySelector('.clock-stage');if(typeof target.animate!=='function'){window.JuiceClock.bounce();return;}activeAnimation=target.animate(r.frames,{duration:r.id==='boss'?1800:1300,easing:'cubic-bezier(.3,.1,.25,1)',iterations:1});window.JuiceClock.tone(700,.1);}
 document.addEventListener('visibilitychange',()=>{if(document.hidden)activeAnimation?.cancel();});
 matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches)activeAnimation?.cancel();});
 function updateCollectionSelection(){document.querySelectorAll('[data-boss-skin]').forEach(b=>b.setAttribute('aria-pressed',String(state.skin===b.dataset.bossSkin)));}
 function renderCollection(){const n=state.solved.length;$('boss-progress').textContent=n+' / '+questions.length+' answered · '+n+' skins + '+n+' moves unlocked';$('boss-count').textContent=n+'/'+rewards.length;$('boss-shortcut').textContent=n===questions.length?'BOSS level complete ✳':'WTF? Earn a new skin ↓';$('boss-open').textContent=n===questions.length?'All unlocked. Play with your toys ✳':'Ask me something weird ↗';
 const grid=$('boss-rewards');grid.replaceChildren();for(let i=0;i<rewards.length;i++){const r=rewards[i],b=document.createElement('button');b.type='button';b.className='boss-reward';b.disabled=i>=n;b.dataset.bossSkin=r.id;b.setAttribute('aria-pressed',String(state.skin===r.id));const swatch=document.createElement('span');swatch.className='boss-mini-swatch';swatch.style.background='linear-gradient(135deg,'+r.colors[1]+','+r.colors[2]+')';swatch.setAttribute('aria-hidden','true');const title=document.createElement('span');title.textContent=r.name;const meta=document.createElement('small');meta.textContent=i<n?r.motion:'Unlock '+(i+1);b.append(swatch,title,meta);b.addEventListener('click',()=>wear(r.id));grid.append(b);}
 const select=$('boss-motion');select.replaceChildren(new Option('Classic bounce',''));for(const r of unlocked())select.add(new Option(r.motion,r.id));select.value=state.motion||'';persist();}
 function open(){if(state.solved.length===questions.length){document.querySelector('.boss-collection').open=true;shell.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});return;}loadQuestion();dialog.showModal();$('boss-question').focus();}
 function loadQuestion(){current=questions.find(q=>!state.solved.includes(q.id));answered=false;if(!current){dialog.close();open();return;}const r=rewards[state.solved.length];$('boss-category').textContent=current.category;$('boss-question-count').textContent='FILE '+String(state.solved.length+1).padStart(2,'0')+' / '+questions.length;$('boss-question').textContent=current.question;$('boss-prize').textContent='Unlock '+r.name+' + '+r.motion;$('boss-feedback').textContent='';$('boss-reveal').hidden=true;$('boss-choices').replaceChildren();
 const order=current.choices.map((text,index)=>({text,index}));for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}
 for(const choice of order){const b=document.createElement('button');b.type='button';b.textContent=choice.text;b.dataset.choice=choice.index;b.addEventListener('click',()=>answer(choice.index,b));$('boss-choices').append(b);}}
 function answer(index,button){if(answered||state.solved.includes(current.id))return;if(index!==current.answer){button.disabled=true;button.classList.add('boss-wrong');$('boss-feedback').textContent='Not that one. Have another crack.';return;}
 answered=true;state.solved.push(current.id);const reward=rewards[state.solved.length-1];state.motion=reward.id;persist();renderCollection();wear(reward.id);document.querySelectorAll('#boss-choices button').forEach(b=>b.disabled=true);button.classList.add('boss-correct');$('boss-feedback').textContent='Correct. '+reward.name+' + '+reward.motion+' unlocked!';$('boss-explanation').textContent=current.explanation;$('boss-source').textContent='Evidence: '+current.source+' ↗';$('boss-source').href=current.url;$('boss-reveal').hidden=false;$('boss-next').textContent=state.solved.length===questions.length?'All unlocked. BOSS wins ✳':'Next weird fact →';window.JuiceClock.tone(880,.16);}
 $('boss-open').addEventListener('click',open);$('boss-next').addEventListener('click',()=>{if(state.solved.length===questions.length){dialog.close();open();}else{loadQuestion();$('boss-question').focus();}});$('boss-wear').addEventListener('click',()=>{dialog.close();window.scrollTo({top:0,behavior:'instant'});play();});$('boss-motion').addEventListener('change',e=>{state.motion=allowed(e.target.value)?e.target.value:null;persist();play();});$('boss-preview').addEventListener('click',play);
 $('play').addEventListener('click',()=>{if(state.motion)play();});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
 renderCollection();if(state.skin)wear(state.skin);
 window.BossTrivia={getProgress:()=>({solved:[...state.solved],skin:state.skin,motion:state.motion}),open};
})();
